name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment only on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js (optional for certain static sites)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build static site (optional if using a build process)
      run: |
        # If you use a build step (like npm run build), add it here. For a basic site, this is not necessary.

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Publish the current directory (root of your repository)
